name: Flutter CI (Feature Branch)

on:
  push:
    branches:
      - feature/dev-s1-use-CI/CD-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # optional (agar test hai)
      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --release